
TEMPLATE = lib
TARGET = SystemC
DESTDIR = $$PJDIR/lib
CONFIG += staticlib c++17
INCLUDEPATH += ./src
DEPENDPATH += ./src
OBJECTS_DIR = $$PJDIR/temp/$$TARGET
MOC_DIR = $$OBJECTS_DIR
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles


build_pass:CONFIG( debug, debug|release ) {
  #  QMAKE_CXXFLAGS *= /vmg /Od /ZI /RTC1 /Uinterface
} else {
 #   QMAKE_CXXFLAGS *= /vmg /Zi /FD /EHsc /MT /W3
}

HEADERS += src/systemc.h \
    src/tlm.h
SOURCES += src/sysc/kernel/sc_main.cpp \
    src/sysc/kernel/sc_main_main.cpp
HEADERS += src/sysc/communication/sc_buffer.h \
    src/sysc/communication/sc_clock.h \
    src/sysc/communication/sc_clock_ports.h \
    src/sysc/communication/sc_communication_ids.h \
    src/sysc/communication/sc_event_finder.h \
    src/sysc/communication/sc_event_queue.h \
    src/sysc/communication/sc_export.h \
    src/sysc/communication/sc_fifo.h \
    src/sysc/communication/sc_fifo_ifs.h \
    src/sysc/communication/sc_fifo_ports.h \
    src/sysc/communication/sc_host_mutex.h \
    src/sysc/communication/sc_host_semaphore.h \
    src/sysc/communication/sc_interface.h \
    src/sysc/communication/sc_mutex.h \
    src/sysc/communication/sc_mutex_if.h \
    src/sysc/communication/sc_port.h \
    src/sysc/communication/sc_prim_channel.h \
    src/sysc/communication/sc_semaphore.h \
    src/sysc/communication/sc_signal.h \
    src/sysc/communication/sc_signal_ifs.h \
    src/sysc/communication/sc_signal_ports.h \
    src/sysc/communication/sc_signal_resolved.h \
    src/sysc/communication/sc_signal_resolved_ports.h \
    src/sysc/communication/sc_signal_rv.h \
    src/sysc/communication/sc_signal_rv_ports.h \
    src/sysc/communication/sc_writer_policy.h \
    src/sysc/datatypes/bit/sc_bit.h \
    src/sysc/datatypes/bit/sc_bit_ids.h \
    src/sysc/datatypes/bit/sc_bit_proxies.h \
    src/sysc/datatypes/bit/sc_bv.h \
    src/sysc/datatypes/bit/sc_bv_base.h \
    src/sysc/datatypes/bit/sc_logic.h \
    src/sysc/datatypes/bit/sc_lv.h \
    src/sysc/datatypes/bit/sc_lv_base.h \
    src/sysc/datatypes/bit/sc_proxy.h \
    src/sysc/datatypes/fx/fx.h \
    src/sysc/datatypes/fx/scfx_ieee.h \
    src/sysc/datatypes/fx/scfx_mant.h \
    src/sysc/datatypes/fx/scfx_other_defs.h \
    src/sysc/datatypes/fx/scfx_params.h \
    src/sysc/datatypes/fx/scfx_pow10.h \
    src/sysc/datatypes/fx/scfx_rep.h \
    src/sysc/datatypes/fx/scfx_string.h \
    src/sysc/datatypes/fx/scfx_utils.h \
    src/sysc/datatypes/fx/sc_context.h \
    src/sysc/datatypes/fx/sc_fix.h \
    src/sysc/datatypes/fx/sc_fixed.h \
    src/sysc/datatypes/fx/sc_fxcast_switch.h \
    src/sysc/datatypes/fx/sc_fxdefs.h \
    src/sysc/datatypes/fx/sc_fxnum.h \
    src/sysc/datatypes/fx/sc_fxnum_observer.h \
    src/sysc/datatypes/fx/sc_fxtype_params.h \
    src/sysc/datatypes/fx/sc_fxval.h \
    src/sysc/datatypes/fx/sc_fxval_observer.h \
    src/sysc/datatypes/fx/sc_fx_ids.h \
    src/sysc/datatypes/fx/sc_ufix.h \
    src/sysc/datatypes/fx/sc_ufixed.h \
    src/sysc/datatypes/int/sc_bigint.h \
    src/sysc/datatypes/int/sc_biguint.h \
    src/sysc/datatypes/int/sc_int.h \
    src/sysc/datatypes/int/sc_int_base.h \
    src/sysc/datatypes/int/sc_int_ids.h \
    src/sysc/datatypes/int/sc_length_param.h \
    src/sysc/datatypes/int/sc_nbdefs.h \
    src/sysc/datatypes/int/sc_nbexterns.h \
    src/sysc/datatypes/int/sc_nbutils.h \
    src/sysc/datatypes/int/sc_signed.h \
    src/sysc/datatypes/int/sc_uint.h \
    src/sysc/datatypes/int/sc_uint_base.h \
    src/sysc/datatypes/int/sc_unsigned.h \
    src/sysc/datatypes/misc/sc_concatref.h \
    src/sysc/datatypes/misc/sc_value_base.h \
    src/sysc/kernel/sc_attribute.h \
    src/sysc/kernel/sc_cmnhdr.h \
    src/sysc/kernel/sc_constants.h \
    src/sysc/kernel/sc_cor.h \
    src/sysc/kernel/sc_cor_fiber.h \
    src/sysc/kernel/sc_cthread_process.h \
    src/sysc/kernel/sc_dynamic_processes.h \
    src/sysc/kernel/sc_event.h \
    src/sysc/kernel/sc_except.h \
    src/sysc/kernel/sc_externs.h \
    src/sysc/kernel/sc_join.h \
    src/sysc/kernel/sc_kernel_ids.h \
    src/sysc/kernel/sc_macros.h \
    src/sysc/kernel/sc_method_process.h \
    src/sysc/kernel/sc_module.h \
    src/sysc/kernel/sc_module_name.h \
    src/sysc/kernel/sc_module_registry.h \
    src/sysc/kernel/sc_name_gen.h \
    src/sysc/kernel/sc_object.h \
    src/sysc/kernel/sc_object_int.h \
    src/sysc/kernel/sc_object_manager.h \
    src/sysc/kernel/sc_phase_callback_registry.h \
    src/sysc/kernel/sc_process.h \
    src/sysc/kernel/sc_process_handle.h \
    src/sysc/kernel/sc_reset.h \
    src/sysc/kernel/sc_runnable.h \
    src/sysc/kernel/sc_runnable_int.h \
    src/sysc/kernel/sc_sensitive.h \
    src/sysc/kernel/sc_simcontext.h \
    src/sysc/kernel/sc_simcontext_int.h \
    src/sysc/kernel/sc_spawn.h \
    src/sysc/kernel/sc_spawn_options.h \
    src/sysc/kernel/sc_status.h \
    src/sysc/kernel/sc_thread_process.h \
    src/sysc/kernel/sc_time.h \
    src/sysc/kernel/sc_ver.h \
    src/sysc/kernel/sc_wait.h \
    src/sysc/kernel/sc_wait_cthread.h \
    src/sysc/packages/boost/bind.hpp \
    src/sysc/packages/boost/config.hpp \
    src/sysc/packages/boost/detail/endian.hpp \
    src/sysc/packages/boost/mem_fn.hpp \
    src/sysc/packages/boost/ref.hpp \
    src/sysc/packages/boost/utility/enable_if.hpp \
    src/sysc/packages/boost/utility/string_view.hpp \
    src/sysc/packages/boost/utility/string_view_fwd.hpp \
    src/sysc/tracing/sc_trace.h \
    src/sysc/tracing/sc_trace_file_base.h \
    src/sysc/tracing/sc_tracing_ids.h \
    src/sysc/tracing/sc_vcd_trace.h \
    src/sysc/tracing/sc_wif_trace.h \
    src/sysc/utils/sc_hash.h \
    src/sysc/utils/sc_iostream.h \
    src/sysc/utils/sc_list.h \
    src/sysc/utils/sc_machine.h \
    src/sysc/utils/sc_mempool.h \
    src/sysc/utils/sc_pq.h \
    src/sysc/utils/sc_pvector.h \
    src/sysc/utils/sc_report.h \
    src/sysc/communication/sc_semaphore_if.h \
    src/sysc/utils/sc_report_handler.h \
    src/sysc/utils/sc_stop_here.h \
    src/sysc/utils/sc_string.h \
    src/sysc/utils/sc_string_view.h \
    src/sysc/utils/sc_temporary.h \
    src/sysc/utils/sc_typeindex.h \
    src/sysc/utils/sc_utils_ids.h \
    src/sysc/utils/sc_vector.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_analysis.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_analysis_fifo.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_analysis_if.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_analysis_port.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_analysis_triple.h \
    src/tlm_core/tlm_1/tlm_analysis/tlm_write_if.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_1_interfaces/tlm_core_ifs.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_1_interfaces/tlm_fifo_ifs.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_1_interfaces/tlm_master_slave_ifs.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_1_interfaces/tlm_tag.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_adapters/tlm_adapters.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_fifo/circular_buffer.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_fifo/tlm_fifo.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_fifo/tlm_fifo_peek.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_fifo/tlm_fifo_put_get.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_fifo/tlm_fifo_resize.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_req_rsp_channels/tlm_put_get_imp.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_channels/tlm_req_rsp_channels/tlm_req_rsp_channels.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_ports/tlm_event_finder.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_ports/tlm_nonblocking_port.h \
    src/tlm_core/tlm_1/tlm_req_rsp/tlm_req_rsp.h \
    src/tlm_core/tlm_2/tlm_2_interfaces/tlm_2_interfaces.h \
    src/tlm_core/tlm_2/tlm_2_interfaces/tlm_dmi.h \
    src/tlm_core/tlm_2/tlm_2_interfaces/tlm_fw_bw_ifs.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_array.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_endian_conv.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_generic_payload.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_gp.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_helpers.h \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_phase.h \
    src/tlm_core/tlm_2/tlm_quantum/tlm_global_quantum.h \
    src/tlm_core/tlm_2/tlm_quantum/tlm_quantum.h \
    src/tlm_core/tlm_2/tlm_sockets/tlm_base_socket_if.h \
    src/tlm_core/tlm_2/tlm_sockets/tlm_initiator_socket.h \
    src/tlm_core/tlm_2/tlm_sockets/tlm_sockets.h \
    src/tlm_core/tlm_2/tlm_sockets/tlm_target_socket.h \
    src/tlm_core/tlm_2/tlm_version.h \
    src/tlm_utils/convenience_socket_bases.h \
    src/tlm_utils/instance_specific_extensions.h \
    src/tlm_utils/instance_specific_extensions_int.h \
    src/tlm_utils/multi_passthrough_initiator_socket.h \
    src/tlm_utils/multi_passthrough_target_socket.h \
    src/tlm_utils/multi_socket_bases.h \
    src/tlm_utils/passthrough_target_socket.h \
    src/tlm_utils/peq_with_cb_and_phase.h \
    src/tlm_utils/peq_with_get.h \
    src/tlm_utils/simple_initiator_socket.h \
    src/tlm_utils/simple_target_socket.h \
    src/tlm_utils/tlm_quantumkeeper.h
SOURCES += src/sysc/kernel/sc_attribute.cpp \
    src/sysc/datatypes/bit/sc_bit.cpp \
    src/sysc/datatypes/bit/sc_bv_base.cpp \
    src/sysc/communication/sc_clock.cpp \
    src/sysc/datatypes/misc/sc_concatref.cpp \
    src/sysc/kernel/sc_cor_fiber.cpp \
    src/sysc/kernel/sc_cthread_process.cpp \
    src/sysc/kernel/sc_event.cpp \
    src/sysc/communication/sc_event_finder.cpp \
    src/sysc/communication/sc_event_queue.cpp \
    src/sysc/kernel/sc_except.cpp \
    src/sysc/communication/sc_export.cpp \
    src/sysc/datatypes/fx/sc_fxcast_switch.cpp \
    src/sysc/datatypes/fx/sc_fxdefs.cpp \
    src/sysc/datatypes/fx/sc_fxnum.cpp \
    src/sysc/datatypes/fx/sc_fxnum_observer.cpp \
    src/sysc/datatypes/fx/sc_fxtype_params.cpp \
    src/sysc/datatypes/fx/sc_fxval.cpp \
    src/sysc/datatypes/fx/sc_fxval_observer.cpp \
    src/sysc/utils/sc_hash.cpp \
    src/sysc/datatypes/int/sc_int_base.cpp \
    src/sysc/datatypes/int/sc_int_mask.cpp \
    src/sysc/communication/sc_interface.cpp \
    src/sysc/kernel/sc_join.cpp \
    src/sysc/datatypes/int/sc_length_param.cpp \
    src/sysc/utils/sc_list.cpp \
    src/sysc/datatypes/bit/sc_logic.cpp \
    src/sysc/datatypes/bit/sc_lv_base.cpp \
    src/sysc/utils/sc_mempool.cpp \
    src/sysc/kernel/sc_method_process.cpp \
    src/sysc/kernel/sc_module.cpp \
    src/sysc/kernel/sc_module_name.cpp \
    src/sysc/kernel/sc_module_registry.cpp \
    src/sysc/communication/sc_mutex.cpp \
    src/sysc/kernel/sc_name_gen.cpp \
    src/sysc/datatypes/int/sc_nbexterns.cpp \
    src/sysc/datatypes/int/sc_nbutils.cpp \
    src/sysc/kernel/sc_object.cpp \
    src/sysc/kernel/sc_object_manager.cpp \
    src/sysc/kernel/sc_phase_callback_registry.cpp \
    src/sysc/communication/sc_port.cpp \
    src/sysc/utils/sc_pq.cpp \
    src/sysc/communication/sc_prim_channel.cpp \
    src/sysc/kernel/sc_process.cpp \
    src/sysc/utils/sc_report.cpp \
    src/sysc/utils/sc_report_handler.cpp \
    src/sysc/kernel/sc_reset.cpp \
    src/sysc/communication/sc_semaphore.cpp \
    src/sysc/kernel/sc_sensitive.cpp \
    src/sysc/communication/sc_signal.cpp \
    src/sysc/communication/sc_signal_ports.cpp \
    src/sysc/communication/sc_signal_resolved.cpp \
    src/sysc/communication/sc_signal_resolved_ports.cpp \
    src/sysc/datatypes/int/sc_signed.cpp \
    src/sysc/kernel/sc_simcontext.cpp \
    src/sysc/kernel/sc_spawn_options.cpp \
    src/sysc/utils/sc_stop_here.cpp \
    src/sysc/utils/sc_string.cpp \
    src/sysc/kernel/sc_thread_process.cpp \
    src/sysc/kernel/sc_time.cpp \
    src/sysc/tracing/sc_trace.cpp \
    src/sysc/tracing/sc_trace_file_base.cpp \
    src/sysc/datatypes/int/sc_uint_base.cpp \
    src/sysc/datatypes/int/sc_unsigned.cpp \
    src/sysc/utils/sc_utils_ids.cpp \
    src/sysc/datatypes/misc/sc_value_base.cpp \
    src/sysc/tracing/sc_vcd_trace.cpp \
    src/sysc/utils/sc_vector.cpp \
    src/sysc/kernel/sc_ver.cpp \
    src/sysc/kernel/sc_wait.cpp \
    src/sysc/kernel/sc_wait_cthread.cpp \
    src/sysc/tracing/sc_wif_trace.cpp \
    src/sysc/datatypes/fx/scfx_mant.cpp \
    src/sysc/datatypes/fx/scfx_pow10.cpp \
    src/sysc/datatypes/fx/scfx_rep.cpp \
    src/sysc/datatypes/fx/scfx_utils.cpp \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_gp.cpp \
    src/tlm_core/tlm_2/tlm_generic_payload/tlm_phase.cpp \
    src/tlm_core/tlm_2/tlm_quantum/tlm_global_quantum.cpp \
    src/tlm_utils/convenience_socket_bases.cpp \
    src/tlm_utils/instance_specific_extensions.cpp
